### ISSUE TITLE
Choosing which containers to update.

### ISSUE THREAD

**Issue by maanoobh** [mag37/dockcheck#1]
Hi,

I think it would be better if there was an option to choose which containers to update.

For example, it would return a numbered list of containers that have updates, and it would expect a comma separated list of numbers to update or update them all.

Thank you for the script, it's very convenient.

**Comment by mag37** [comment]
Thank you, good suggestion. I was thinking of this early on but then had to start squash other bugs. Might come back around to this again!

**Comment by mag37** [comment]
There's now an experimental_dockcheck.sh to try this, will make it main if everything seems to be working as intended.
https://github.com/mag37/dockcheck/blob/main/experimental_dockcheck.sh

**Comment by mag37** [comment]
This is now in main branch. Closing.
