### ISSUE TITLE
works but does not replace existing containers

### ISSUE THREAD

**Issue by Milor123** [mag37/dockcheck#105]
I am running it with podman

``` bash
 #!/usr/bin/env bash
sudo rm /usr/bin/docker
sudo ln -s /usr/bin/podman /usr/bin/docker
./dockcheck.sh -s -f -p

```

but i get it:

``` bash

hat name is already in use, or use --replace to instruct Podman to do so.
n8n
WARN[0000] Error descending into path /dev/vboxusb: open /dev/vboxusb: permission denied 
WARN[0000] Error descending into path /dev/vboxusb: open /dev/vboxusb: permission denied 
WARN[0000] Error descending into path /dev/vboxusb: open /dev/vboxusb: permission denied 
WARN[0000] Error descending into path /dev/vboxusb: open /dev/vboxusb: permission denied 
WARN[0000] Error descending into path /dev/vboxusb: open /dev/vboxusb: permission denied 
WARN[0000] Error descending into path /dev/vboxusb: open /dev/vboxusb: permission denied 
WARN[0000] Error descending into path /dev/vboxusb: open /dev/vboxusb: permission denied 

Now updating (12/14): ollama
Trying to pull docker.io/ollama/ollama:latest...
Getting image source signatures
Copying blob 6414378b6477 skipped: already exists  
Copying blob 6414378b6477 skipped: already exists  
Copying blob 6043d7740b8f done   | 
Copying blob 6414378b6477 skipped: already exists  
Copying blob 99ef3d1416df done   | 
Copying blob 75a058f715a3 done   | 
Copying blob 96587fbdc30e done   | 
Copying blob 5fb1e92c3720 done   | 
Copying blob 048c8c4ad84e done   | 
Copying blob d05d3a05f8c0 done   | 
Copying config a250fd898e done   | 
Writing manifest to image destination
a250fd898ed6434c040167c91ab95ac8707a5c7c987977b06efddb2dd0d97eff
>>>> Executing external compose provider "/usr/bin/docker-compose". Please see podman-compose(1) for how to disable this message. <<<<

ollama
>>>> Executing external compose provider "/usr/bin/docker-compose". Please see podman-compose(1) for how to disable this message. <<<<



>>>> Executing external compose provider "/usr/bin/docker-compose". Please see podman-compose(1) for how to disable this message. <<<<

ollama
>>>> Executing external compose provider "/usr/bin/docker-compose". Please see podman-compose(1) for how to disable this message. <<<<

Error: adding pod to state: name "pod_Ollama" is in use: pod already exists
Error: creating container storage: the container name "ollama" is already in use by 6c680b7e11bac888fd314bbdc34e7913057679d3c1d817feb18a87996e42e93c. You have to remove that container to be able to reuse that name: that name is already in use, or use --replace to instruct Podman to do so.
ollama

```

I am in manjaro guys, is it a permission problem? What should I do, it update my images but dont replace container :/

**Comment by mag37** [comment]
Hey, it has nothing to do with permissions or distribution I'm afraid.

Podman just isn't supported. If you check the [Dependencies](https://github.com/mag37/dockcheck#nut_and_bolt-dependencies) in the readme it mentions nothing about podman. Only docker and docker compose.

I've been considering supporting Podman - but currently there's quite a few ways to run Podman. 

- Regular `podman run`
- With [podman compose](https://github.com/containers/podman-compose)
- Old systemd way with [`podman-generate-systemd`](https://man.archlinux.org/man/podman-generate-systemd.1.en)
- New (my preferred) systemd way with [quadlets](https://mag37.org/posts/guide_podman_quadlets/).
- Different solutions with Kubernetes.

And probably more.

You could maybe use the `-r` flag and then manually recreate all containers but that doesn't really solve it completely.

**Comment by mag37** [comment]
I'd be happy to do more troubleshooting if you reply further on how you run containers and how you'd like to use dockcheck.
But if nothing more is posted I'll close the issue.

**Comment by mag37** [comment]
Closed. Discussion about Podman support will be going on elsewhere.

**Comment by mag37** [comment]
@Milor123  There's now a wonderful fork [sudo-kraken/podcheck](https://github.com/sudo-kraken/podcheck) to support Podman, make sure to check that out!

**Comment by Milor123** [comment]
> @Milor123 There's now a wonderful fork [sudo-kraken/podcheck](https://github.com/sudo-kraken/podcheck) to support Podman, make sure to check that out!

Amazing man! Thank u very much, excuse me for dont reply before. I am noob in this.
