### ISSUE TITLE
dockcheck notifies of updates before DSM sees them

### ISSUE THREAD

**Issue by yoyoma2** [mag37/dockcheck#114]
The DSM 7.2.x Container Manager now has an "Update" button in the GUI for outdated images but it checks rarely and it's confusing to get the notification from dockcheck while the "Update" button isn't being shown.

This one line change ensures the DSM GUI will let you update an image after dockcheck notifies you that an update is available.

```
diff --git a/notify_templates/notify_DSM.sh b/notify_templates/notify_DSM.sh
index d9a0cd9..3daa987 100644
--- a/notify_templates/notify_DSM.sh
+++ b/notify_templates/notify_DSM.sh
@@ -49,4 +49,7 @@ Content-Transfer-Encoding: 7bit
 $MessageBody
  From $SenderName
 __EOF
+
+# This ensures DSM's container manager will also see the update
+/var/packages/ContainerManager/target/tool/image_upgradable_checker
 }

```
DSM is slow to notice updates as [discussed here](https://community.synology.com/enu/forum/1/post/189972).

**Comment by mag37** [comment]
That template is your child 😁   
If you want, make a PR and I'll merge it, otherwise I'll just edit it (but you should have the credit).

**Comment by yoyoma2** [comment]
I recently deleted my dockcheck fork thinking it's feature complete so you can just edit it. Thanks for being so nice about giving credit!

**Comment by mag37** [comment]
Sorted, thank you again!
Closing.
