### ISSUE TITLE
Add default option

### ISSUE THREAD

**Issue by BarnardCollier** [mag37/dockcheck#14]
Great script. Love it.  Already copied a whole section to one of my project.

Would recommend added UpdYes="no" just before line 20 of the dockcheck.sh script so that if invoked without option, it defaults to simply checking status of docker images.

**Comment by mag37** [comment]
Glad you like it and that it can inspire other projects!

Earlier I had the user select yes/no prior to selecting the numbers (all or specific) but it felt counter intuitive. Back then there was a default "no".
Now I've removed the yes/no-prompt but still require the user to pick all or specific before continuing.

You still got the option to run it with either -n or -y flags for only check or to auto update.
I'll take a look on the yes/no - leftovers and see if I can clean it some and see if a "default no" is necessary in the future!
