### ISSUE TITLE
"No updates available" when updates are available (Portainer)

### ISSUE THREAD

**Issue by iparr** [mag37/dockcheck#19]
I'm running [Diun](https://crazymax.dev/diun/) currently to notify me when containers have new images available.

Today, for example, it suggests:
```
Tue, 14 Feb 2023 00:00:03 UTC INF Image update found image=lscr.io/linuxserver/radarr:latest provider=docker
Tue, 14 Feb 2023 00:00:03 UTC INF Image update found image=docker.io/louislam/uptime-kuma:latest provider=docker
Tue, 14 Feb 2023 00:00:03 UTC INF Image update found image=docker.io/linuxserver/plex:latest provider=docker
Tue, 14 Feb 2023 00:00:04 UTC INF Image update found image=docker.io/linuxserver/transmission:latest provider=docker
Tue, 14 Feb 2023 00:00:04 UTC INF Image update found image=docker.io/linuxserver/jackett:latest provider=docker
```

But running `./dockcheck.sh` returns:
```
Containers on latest version:
diun
jackett
plex
portainer
radarr
transmission
uptime-kuma
```

It's good that it's at least detecting what containers I have, but obviously the two things cannot be true. Updates are available.

This has happened previously with different updates. Dockcheck has not yet suggested any available updates when updates have been available.

Have I misunderstood this tool?

**Comment by mag37** [comment]
Err. No this tool is for upgrading. Comparing the digests of local VS repo.
This needs some troubleshooting! Maybe the registry digest doesn't change with every minor update? Should do thou.. 

So if you'd try `docker compose pull` on one of the containers Diun saying got an update, do it pull an update?

**Comment by iparr** [comment]
That was my understanding: that this tool would tell me when an upgrade was available and then pull it or at least let me know that I could pull it.

I don't have the docker composer tooling, I installed it but I have no idea what to do. `docker compose pull` on any container name results in `no configuration file provided: not found`. I'm using Portainer - I presume that method of managing images isn't compatible with the command line (although I do a limited number of Docker things in the CLI). I can use Portainer to pull an update and it do pull an update.

I'm not expecting you to give me a Docker tutorial! I just thought this was close to what I needed.

**Comment by mag37** [comment]
Ah yes, this tool is mainly to use together with docker compose. Docker Run (and portainer if not using **Stacks** which is a wrapper for compose) is behaving differently and will not properly update your containers.  

I have not used Portainer in ages, so I cant speak for how it behaves when images for running services are updated manually, but Docker Run containers needs to be rebuilt - aka stopped, removed and re-created with the same `docker run ...` command.   

Though I figured you'd still see available updates the same way. 

What if you try running these commands while standing in the directory that got the `regctl` binary.   
(replace **radarr** with a name of a container that got updates)
```
RepoUrl=$(docker inspect "radarr" --format='{{.Config.Image}}')
docker image inspect "$RepoUrl" --format '{{.RepoDigests}}'
regctl image digest --list "$RepoUrl"
 ```

**Comment by iparr** [comment]
I get `[lscr.io/linuxserver/radarr@sha256:0bd872c0f5c2ff7a5a89f3d1d85459ab5489674e8c1e7817484d26fb45d9ca02]` on the 2nd, then nothing on the final.

**Comment by mag37** [comment]
Looks good with the first hash, though odd because I get this output: 

```
regctl image digest --list "lscr.io/linuxserver/radarr:latest"
sha256:57dd072588d346d5cab39509296ab9c43cd948bb4bd3d143b24f76e1d52b193f
```

You've got regctl in the directory? Oh sorry you might need write `./regctl` instead. Try again with that if you didnt.

**Comment by iparr** [comment]
Yeah, I popped the `./` on but no output at all.

**Comment by mag37** [comment]
That's very odd. Thank you for trying. 
Looks like you've got issues with regctl then?

I can't help you right now. But I'll spin up some containers with Portainer in a VM to see if there's clashes. When I have time.

**Comment by iparr** [comment]
Okay, this is leading to clues - nice one.

On first run, the script tries to `curl` regctl if not installed. If curl is not installed, then it just creates an empty file called `regctl`. I installed curl, removed that blank file and then ran the script again and it's detecting which containers have updates available.

When I try to update it says `uptime-kuma has no compose labels, probably started with docker run - skipping` but this is a whole other issue, probably related to the Portainer-based way I am doing things. So feel free to close this.

**Comment by mag37** [comment]
Oh that's great! Got me sweating a bit 😅. Good to find odd quirks still! 

Well I should probably make some sanitation/check if curl doesn't exist and look into some error handling.

And indeed - that's because your containers are started with `docker run` and don't have the same functionality. You can still allow pulling images with -r flag, but actually using the updates image is depending on how Portainer is handling re-creation of the containers.

Thank you for the troubleshooting, I'll close this and add some stuff to my to-do-list!

**Comment by mag37** [comment]
Added fixes to my pre-release draft.
```
...
    if [[ $(builtin type -P curl) ]]; then curl -L $RegUrl > ./regctl ; chmod +x ./regctl ; regbin="./regctl" ;
    elif [[ $(builtin type -P wget) ]]; then wget $RegUrl -O ./regctl ; chmod +x ./regctl ; regbin="./regctl" ;
    else
      printf "%s\n" "curl/wget not available - get regctl manually from the repo link, quitting."
    fi
...
### final check if binary is correct
$regbin version &> /dev/null  || { printf "%s\n" "regctl is not working - try to remove it and re-download it, exiting."; exit; }

```

Closing!
