### ISSUE TITLE
Custom .env file support

### ISSUE THREAD

**Issue by jokob-sk** [mag37/dockcheck#24]
Hi there!

Nice script :) 

Not sure how difficult it would be to support this kind of setup.

Folder structure:

```
_ Root docker folder
   |\_ pialert
   |    \_ docker-compose.yml
   \_ syncthing
   |     \_docker-compose.yml
   \_ .env_nas
```

Currently, I have to go thru (`cd pialert`) the folders and run the following in each folder:

` sudo docker-compose --env-file ../.env_nas up  -d`

This resolves all environmental variables if present.

Anyway, I know this is a more complex setup, and not sure if your script is intended to solve updates in such a setup.

Either way, great work!

**Comment by mag37** [comment]
I've made a potential fix for this to the [testing_019 branch](https://github.com/mag37/dockcheck/tree/testing_019). I need to do some more testing before I merge it to main. And re-think if I can do it cleaner :D but seems to work.

If you've got time, please do test it and reply if you hit errors.

**Comment by jokob-sk** [comment]
Very nice, impressed by how you got it working without having to specify my custom file name. Works great!

**Comment by mag37** [comment]
Wonderful! Glad it worked, thank you for submitting the issue.
I'll merge it with main now.
