### ISSUE TITLE
:develop vs :latest

### ISSUE THREAD

**Issue by nodecentral** [mag37/dockcheck#26]
Hi, 

Just an FYI - as I use DIUN for push notification, I’ve noticed that as some of my containers use the `:develop` build, rather than `:latest` ; dockcheck does not pick them up. 

I assume something similar happens when you use a specific build to `:4.6` ?

Maybe there is scope in a future update to add these to the UI, perhaps highlighting them in a different section.

**Comment by mag37** [comment]
You're right! 
I probably lost track of this when doing other revamps of the update-procedure. I'll make a fix right away to v0.1.9 
Just gotta change the pull variable to actually use the specific image-tag again.

Thank you for alerting me! Quickfixed in [this commit](https://github.com/mag37/dockcheck/commit/e7544503009eecebb4b36970b5de1d9ace7b9886) to main (v0.1.9)

**Comment by nodecentral** [comment]
Many thanks, quick follow up.. As I like to have a clean ‘inbox’ :-) would it be possible not to put those containers that have a specific version, in the “Containers with updates’ box ?  Their docker_compose is hard coded to a version, so while it’s good to know there is an update it’s not one I want to apply in any hurry (so more monitor it). - where as something that’s set up to pull the latest can move quickly..  (this will help with future triggering via your the UI of updates :-)  )
