### ISSUE TITLE
No such file or directory error when updating multiple containers

### ISSUE THREAD

**Issue by vrob01** [mag37/dockcheck#27]
I have just updated to the latest version (0.2.0) and tried to run dockcheck. It has successfully updated one of my containers, but the rest of them fails. Here's the output of a re-run of dockcheck (and therefore missing the successful update):
```
$ LANG=c ./dockcheck.sh -a
. . . . . . .
Containers on latest version:
adguard
nginxproxymanager-app-1
nginxproxymanager-db-1

Containers with updates available:
filezilla
heimdall
portainer
unifi-controller
./dockcheck.sh: line 178: cd: /opt/docker-compose/tools/docker-compose.yml,/opt/docker-compose/tools: No such file or directory
Path error - skipping filezilla
./dockcheck.sh: line 178: cd: /opt/docker-compose/tools/docker-compose.yml,/opt/docker-compose/tools: No such file or directory
Path error - skipping heimdall
./dockcheck.sh: line 178: cd: /opt/docker-compose/tools/docker-compose.yml,/opt/docker-compose/tools: No such file or directory
Path error - skipping portainer
./dockcheck.sh: line 178: cd: /opt/docker-compose/tools/docker-compose.yml,/opt/docker-compose/tools: No such file or directory
Path error - skipping unifi-controller
All done!
```

```
# tree /opt/docker-compose
/opt/docker-compose
├── adguard
│   └── docker-compose.yml
├── LICENSE
├── nginxproxymanager
│   └── docker-compose.yml
├── README.md
├── teamspeak
│   └── docker-compose.yml
└── tools
    ├── docker-compose.override.yml
    └── docker-compose.yml
```

**Comment by mag37** [comment]
That's odd, thank you for the output and tree. I'll try to troubleshoot this later - I've just done a test-run and did not have any issues.
Seems like the tools-dir is referenced in all containers? How's that?

Would you mind pasting the output from `docker inspect "heimdall" --format '{{ index .Config.Labels "com.docker.compose.project.config_files" }}'` ?
And swap `heimdall` to whatever container that's not working.

Thank you.

**Comment by mag37** [comment]
Oh I just realised its due to the `docker-compose.override.yml`!
I have not taken into account that the container can be started with several compose-files so I've just blatantly taken the value of `com.docker.compose.project.config_files` as one single entity.

I'll need see if I've got time to rework this! Probably by splitting the values from said variable and using them as multiple -f flags to the compose.

**Comment by mag37** [comment]
Added a hacky potential fix that'll allow custom/multiple override-files.
I tried mirroring your setup in my lab env and did successful testing there, but I'd gladly receive some feedback from someone else before I push it to main. Would you mind testing on one of your containers which uses your custom layout?

It's available in the [testing branch](https://github.com/mag37/dockcheck/blob/testing/dockcheck.sh) for now.

**Comment by mag37** [comment]
Implemented in the latest version. If you try it out @vrob01 I'd gladly hear some feedback.

**Comment by vrob01** [comment]
I've just downloaded the latest version and given it a try. Since I haven't updated my containers in a while it was a mix of multi-compose projects and monolithic ones. Both the errorCheck.sh and dockcheck.sh worked perfectly!
Thanks a lot for your work!
