### ISSUE TITLE
Issue on Raspberry Pi 4

### ISSUE THREAD

**Issue by kidstretch** [mag37/dockcheck#3]
Hello, i'm using Portainer to deploy with the following docker compose.

version: '3.2'
services:
  dockcheck-web:
    container_name: dockcheck-web
    image: 'palleri/dockcheck-web:arm'
    restart: unless-stopped
    ports:
      - '87:80'
    volumes:
      - ./data:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock

I checked the logs and i get the following errors:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.224.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.224.2. Set the 'ServerName' directive globally to suppress this message
[Sat Jan 28 08:56:55.171750 2023] [mpm_prefork:notice] [pid 463] AH00163: Apache/2.4.54 (Debian) PHP/8.1.15RC1 configured -- resuming normal operations
[Sat Jan 28 08:56:55.172063 2023] [core:notice] [pid 463] AH00094: Command line: 'apache2 -D FOREGROUND'

My pi's ip is 192.168.1.32, don't know if that helps.

**Comment by mag37** [comment]
Thank you for the comment, this issue is not with my repo but with [Palleri/dockcheck-web](https://github.com/Palleri/dockcheck-web) which uses my script in the backend.
