### ISSUE TITLE
[FEATURE REQUEST] dockcheck updater

### ISSUE THREAD

**Issue by adrianmihalko** [mag37/dockcheck#31]
Hi,

I love this little tool. Please consider to add an update function into dockcheck script itself, so it should be able to automatically download latest dockcheck version.

**Comment by mag37** [comment]
Thank you kindly!
I've been meaning to create an update-function somehow, just haven't had the time lately - but I'll look into it soon!

**Comment by mag37** [comment]
Merged to main, wont really make any effect until next release thou ;) 
But if you'd like to try it out, you could always change the version-number in the local file and let it curl a new file.
