### ISSUE TITLE
Q: Recreates even after dockcheck is ran?

### ISSUE THREAD

**Issue by thehijacker** [mag37/dockcheck#33]
I am running it with ap parametere:

`./dockcheck.sh -ap`

It updates all the images, recreates the containers and purges old images. Once finished I run

`docker-compose up -d`

And all updated containers are again recreated. Why does it recreate them again?

Thank you.

**Comment by thehijacker** [comment]
Have you been able to solve this? Currently I am again doing manual "pull" and "up -d".

**Comment by mag37** [comment]
> Have you been able to solve this? Currently I am again doing manual "pull" and "up -d".

I have not, tried to troubleshoot it without finding the issue..

Did some testing and I see that when I update a service with the script:
- it recreates the container
- the service is the new version
- the digest of the image is the newest version

while still, sometimes when I try `docker-compose up -d` it recreates again without any change between the container before/after the recreation (except for the unique IDs etc).
