### ISSUE TITLE
Exclude containers

### ISSUE THREAD

**Issue by Obsidiannite21** [mag37/dockcheck#34]
Hello,

Love your script. I experiencing one minor bug or maybe it's a feature request? When I exclude a container i.e. photoprism_mariadb, the photoprism container also gets excluded. They are part of the same docker compose file, but are two separate containers so I'm not sure why that's happening. I'm trying to exclude all of the database containers since upgrading databases has been tricky at times. I'd like to use the -a|y flag with -e but currently that isn't going to work the way I'd like it to.

**Comment by mag37** [comment]
Thank you for reporting! Ill look into the logic asap and get back to you.

**Comment by mag37** [comment]
@Obsidiannite21 

I've just pushed a potential fix to the [dev1](https://github.com/mag37/dockcheck/tree/dev1) branch. 
The error I've made was that I did globbing/wildcarding when excluding, so part of a name could match a non-excluded container. 
Now it should be only exact matches, so you'll need to write full, exact names of what to exclude. Separated by comma still.

I'll merge it with main as soon as I've had some more machines testing it. 
You can try if you'd like:
https://github.com/mag37/dockcheck/blob/dev1/dockcheck.sh

**Comment by Obsidiannite21** [comment]
Perfect!! Thank you, I'll test it now and report back.

**Comment by Obsidiannite21** [comment]
Tested and worked correctly! Thanks again!

**Comment by mag37** [comment]
> Tested and worked correctly! Thanks again!

Super! Thank you for reporting and testing. I'll merge with main any day. Just gotta review some minor stuff.

**Comment by mag37** [comment]
[Merged to main](https://github.com/mag37/dockcheck/commit/48bfea9fbfb23fe3114881f6a3f3d88313eeb9bf) - Closing.
