### ISSUE TITLE
New update check doesn't honor -y parameter

### ISSUE THREAD

**Issue by sommerper** [mag37/dockcheck#37]
Hi! I just noticed this with the new update:

❯ cd ~/github/dockcheck/ && ./dockcheck.sh -y -p
New version available! Local: v0.2.3 - Latest: v0.2.4
 Change Notes: Fixes to the Exclude-option to only exclude exact matches. +cleaning
Choose update procedure (or do it manually) - git/curl/[no]:

Which prevents my cron task from running. Maybe you could add another option for automatic updates?

Thank you for a great tool!

**Comment by mag37** [comment]
Great find! I didn't think of that breaking the no-interaction flags.

Did a [quick fix](https://github.com/mag37/dockcheck/commit/6a3198eb083522d0fd8a59ca059d4f9c380576bb) that should solve it. 
If the `-y|a` flag is passed it will just print the "New version.."-info and then skip the self-update interaction (and thereby the update too).

I dont think having scheduled auto self-updates is a great idea, but if you think the option should be there I'll look into it in the future.
