### ISSUE TITLE
Request to update dc_brief.sh

### ISSUE THREAD

**Issue by Obsidiannite21** [mag37/dockcheck#38]
I'm not sure if this is the right place to post this but I didn't know where would be better.

I use the DockCheck Web project (https://github.com/Palleri/dockcheck-web), to send me push notifications when a container needs to be updated. As I'm sure you're aware this project is based on your script. I'm not a coder but it seems that the Docker build is specifically calling dc_brief.sh. You recently updated the script to more accurately filter excluded container, but it doesn't look like this file was updated, so DockCheck web is still using the old exclude parameters. Would you be able to update this @mag37 ? I compared the code and it looks like this would do the trick but I'm more likely to break something than fix it lol:

  [[ "${Excludes[@]}" == ${i} ]] && continue;

**Comment by mag37** [comment]
This is the perfect place to post it :) 
Thank you for reminding me - been meaning to compare the brief-version with main to see if I've missed including changes in it. 

I've just had a quick glance and it's probably be fixable by changing the line to   
`for e in "${Excludes[@]}" ; do [[ "$i" == "$e" ]] && continue 2 ; done `    

But I need to do some testing before I'll publish a change.

**Comment by Obsidiannite21** [comment]
@mag37 Awesome, thank you!

**Comment by mag37** [comment]
I've did some testing and seems to work as expected, will merge to main. 
But I realized the [Palleri/DCW](https://github.com/Palleri/DCW) have a modified file, not updated by my source so I made a pull request :) hopefully it'll resolve your issue.

**Comment by Obsidiannite21** [comment]
Thanks again!!

**Comment by mag37** [comment]
@Obsidiannite21 
Until it's patched you can run this to fix it (replace `dcw` if you've named your contianer differently)   
```sh
docker exec dcw sed -i '19s/^.*$/ for e in "${Excludes[@]}" ; do [[ "$i" == "$e" ]] \&\& continue 2 ; done/' app/dockcheck.sh
```
That'll change the specific line of code in the script in the container.
It's the same change I've pull requested to @Palleri

**Comment by Obsidiannite21** [comment]
Wow, thank you! I appreciate you taking the time to share that with me. It worked except there was 1 minor typo - the / was missing from "/app/dockcheck.sh" just in case anyone else tries to use this. I rebuilt the container and it is excluding things correctly!

**Comment by mag37** [comment]
@Palleri ah didnt realise @Obsidiannite21 used the old project, that should be pulling the `dc_brief.sh` from my project and be fixed already then as I understand it. Neat.

**Comment by Palleri** [comment]
@mag37 Yes correct.
Anyway, thank you for making the pull request to DCW aswell. I will make sure to push it as soon as possible.

**Comment by Obsidiannite21** [comment]
I apologize @mag37 , I forgot the project was old. @Palleri I tried the new project but was having issues, so I reverted to the old. I will give it another try and see if I have the same issues.

**Comment by Palleri** [comment]
@Obsidiannite21 No worries, I am happy to help you to get the new up and running. Just submit an issue on DCW if you have any problems.

**Comment by Obsidiannite21** [comment]
Will do! I'll try it tonight.
