### ISSUE TITLE
Running in systems which needs SUDO before DOCKER command

### ISSUE THREAD

**Issue by napalmz** [mag37/dockcheck#4]
This is not a real issue but more ad implementation...

I've tried using this script in my Unraid system, running from ROOT, and everything was great.
Then I moved to UBUNTU and it wasn't working since it needs a SUDO before running DOCKER commands (you don't run script from ROOT usually).
There are methods to avoid this? Like implementing a "system check" to add a SUDO if it's needed?

Thank you

**Comment by mag37** [comment]
I might look into this i the future. Having a check if the script is launched as root/sudo is easy enough. But I rather think this is a user-issue - I'd suggest adding your user to the docker group if it's the user you manage docker with.

[SOURCE: docker.com docs](https://docs.docker.com/engine/install/linux-postinstall/) 
`sudo usermod -aG docker $USER`
Log out and in again, or do `newgrp docker`  to have effect in current shell.
