### ISSUE TITLE
[FEATURE REQUEST] monochrome mode

### ISSUE THREAD

**Issue by dst78** [mag37/dockcheck#48]
I'm running dockcheck.sh from within a shellscript wrapper to provide logging and email notifications. For that it would be lovely if there was a monochrome option, i.e. `dockcheck.sh -m` which behaves exactly the same but doesn't use color escape code sequences, as they aren't playing well with email.

Thanks for your consideration!

**Comment by mag37** [comment]
I'll look into how I could achieve this without making a mess.
My first thought (without reading up on it) would be to try to set the colors as variables - and if the monochrome-flag is set it'll just set the variables blank.

To avoid having a if-else for every print statement - that'd be messy.

**Comment by mag37** [comment]
I'm still intrigued how you're using this and what's causing errors.

Looked into swapping all printf's to variables, that'd mean it would look like this:
```sh
# currently:
printf "\n\033[0;33mContainers with updates available:\033[0m\n"
# with variables:
printf "\n%bContainers with updates available:%b\n" "$c_yellow" "$c_reset"
```
Or something similar, where the variables would just be set to "" if monochrome option was toggled. Would that make a difference in your use case?

**Comment by mag37** [comment]
Just added a [new branch](https://github.com/mag37/dockcheck/blob/printf_rework/dockcheck.sh), will test it some more before pushing to main. If you can and want to try it, please do and report if it suits your case :)

**Comment by mag37** [comment]
Thank you for testing and giving feedback! And thank you for bringing up the suggestion in the first place.

I'll merge it with main in a minute, just gonna do some minor cleaning while I'm on it.
