### ISSUE TITLE
[Feature] Integration for pushbullet support - script attached

### ISSUE THREAD

**Issue by arpanghosh8453** [mag37/dockcheck#56]
I have used the following script for pushbullet integration, and it's working well. Do you mind integrating it into your supported notification list?

```bash
### DISCLAIMER: This is a third party addition to dockcheck - best effort testing.
# Copy/rename this file to notify.sh to enable the notification snippet. Make sure you have jq package installed and it's on path

send_notification() {
Updates=("$@")
UpdToString=$( printf "%s\n" "${Updates[@]}" )
FromHost=$(hostname)

# platform specific notification code would go here
printf "\nSending pushbullet notification\n"
printf "\nThe following docker containers on %s need to be updated:\n%s\n" "$FromHost" "$UpdToString"
MessageTitle="$FromHost - updates available."
# Setting the MessageBody variable here.
MessageBody="Containers on $FromHost with updates available: $UpdToString"
# Modify to fit your setup:
PushUrl="https://api.pushbullet.com/v2/pushes"
PushToken="Your Pushbullet token here"
# Requires jq to process json data
jq -n --arg title "$MessageTitle" --arg body "$MessageBody" '{body: $body, title: $title, type: "note"}' | curl -sS -o /dev/null --show-error --fail -X POST -H "Access-Token: $PushToken" -H "Content-type: application/json" $PushUrl -d @-
}

```

**Comment by mag37** [comment]
Epic! Thank you.


If you want to, I'd gladly receive a PR for adding the template file. 

Just modify the disclaimer to something like this and its ready
```
### DISCLAIMER: This is a third party addition to dockcheck - best effort testing.
#
# Copy/rename this file to notify.sh to enable the notification snippet.
# Required receiving services must already be set up.
# Modify to fit your setup - set IP and Token
```


Or if you dont wanna make a PR, I can create it and reference you in the commit.

**Comment by arpanghosh8453** [comment]
I did not fork your repo, so I don't have that option; I just copied the dockcheck.sh and a template notification file and modified it based on my needs. If you can include the template file I provided (ofc with suggested disclaimer) to your repo, that will be great for someone with my needs. 

You don't even need to link me, this script is great! Thanks for offering such a nice tool. I update my containers occasionally and watchtower is not best for that purpose. 

Thanks a lot, appreciate the quick response :)

**Comment by mag37** [comment]
Ah no worries! I'll just create the new template file then. Thank you for the contribution!

I'll reference you in the commit at least - happy that people are suggesting and adding to it. And glad to hear you find it useful.

It's now committed, will make a new version-tag soon to include it in updates.
Thank you again!
