### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by msrheidema** [mag37/dockcheck#6]
When trying to run the script I'm running into the following error:

```root@servername:~# ./dockcheck.sh
Required dependency 'regctl' missing, do you want it downloaded? y/[n] y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 8076k  100 8076k    0     0   360k      0  0:00:22  0:00:22 --:--:--  449k
. . . . . . . . . 
Containers on latest version:
fr24feed
cloudflared
mosquitto
unifi

Containers with updates available:
0) ALL
1) mariadb

Do you want to update? y/[n] y
What containers do you like to update? 
Enter number(s) separated by comma (eg. 1,3,4): 0

You've SelectedUpdates:
mariadb
stat /opt/docker-compose.yml: no such file or directory
stat /opt/docker-compose.yml: no such file or directory
```

**Comment by msrheidema** [comment]
Found the error.
docker-compose.**yaml** --> docker-compose.**yml**

Renamed the file and now the script runs no problem. Thanks :)

**Comment by mag37** [comment]
Thank you, I should look into making that flexible instead! Closing the issue for now, but will make it a "known issue" for future improvements.

**Comment by mag37** [comment]
Actually changed my mind, your issue is resolved but the issue in the project is still there.
Reopened!

**Comment by msrheidema** [comment]
You could go for the
`com.docker.compose.project.config_files`
instead of
`com.docker.compose.project.working_dir`


However, my config_file is still *.yaml even though the physical file is *.yml as the data in `com.docker.compose.project.config_files` is information from during the build 🤔

**Comment by mag37** [comment]
Thank you!

I actually worked on exactly that change just now, I'm about to push it to main. Though when I saw your comment I had to do some further testing - seems like if you do `docker compose down` and then `docker compose up -d` it changes `com.docker.compose.project.config_files` too.

**Comment by mag37** [comment]
Added the fix to main - will close this issue later tonight if nothing else comes up. Thank you for the troubleshooting.

And if you've renamed your compose-files to allow for the assumed "name standard" `docker-compose.yml` - either change them back or completely down and up the container.
