### ISSUE TITLE
Progress bar fails with -s option

### ISSUE THREAD

**Issue by yoyoma2** [mag37/dockcheck#63]
If the -s option is used to include stopped containers the progress bar acts funny even dividing by zero when no containers are running. This change makes it work.
```
diff dockcheck.sh dockcheck.sh.original
209c209
< DocCount=$(docker ps $Stopped --filter "name=$SearchName" --format '{{.Names}}' | wc -l)
---
> DocCount=$(docker ps --filter "name=$SearchName" --format '{{.Names}}' | wc -l)
212c212
< ### Check the image-hash of every concerned container VS the registry
---
> ### Check the image-hash of every running container VS the registry
```

**Comment by mag37** [comment]
Good catch! It's pushed to main as a bugfix. 
Thank you, once again!

**Comment by yoyoma2** [comment]
Wow fastest fix ever! Issues get closed when a release happens I assume?

**Comment by mag37** [comment]
Haha, was just a coincidence - I went to check something and saw the issue posted.

I'll close this one manually, it's in the main code already and will be baked into the next release.
