### ISSUE TITLE
Check for old docker-compose binary fails

### ISSUE THREAD

**Issue by xoseperez** [mag37/dockcheck#7]
The old docker-compose binary returns error if called without arguments, so the script thinks it does not exist even if it does. It will probably make sense to ask for version or help

**Comment by mag37** [comment]
Odd! To be cliché: "it does work on my machine" without errors even if called empty.
I'll change it to have the -v flag though, if this is different over different versions. 

Thank you for the report and suggestion!
Closing as fixed.
