### ISSUE TITLE
Readme: add install instructions

### ISSUE THREAD

**Issue by thomas-mc-work** [mag37/dockcheck#73]
What do you think about adding install instructions? A simple variant for a minimal setup foris like this:

    wget -O /usr/local/bin/dockcheck.sh "https://raw.githubusercontent.com/mag37/dockcheck/main/dockcheck.sh" && chmod +x /usr/local/bin/dockcheck.sh

This works also for updates.

The notifiers aren't included. This could be solved like that:

    wget -O- https://api.github.com/repos/mag37/dockcheck/tarball | tar -xz -C "/usr/local/bin" --strip 1 && chmod +x /usr/local/bin/{dockcheck,notify_*}.sh

The drawback is having other files from the repo cluttering the `bin` folder. This could be solved by creating a `release.tar.gz` with each release.

**Comment by mag37** [comment]
Having a simple install instruction/example is a good suggestion! 
Though wget to `/usr/local/bin` would require sudo, as would chmod in the same directory.

And all notify-files isnt required, those are just templates - the user should rather pick  their flavor and modify it to their own notify.sh.

**Comment by thomas-mc-work** [comment]
Alright, that was just an example. The obvious local alternative prefix would be `$HOME/.local` instead of `/usr/local`.

**Comment by mag37** [comment]
Added some minor instructions to the Readme. Thank you for the suggestion!
Closing.

**Comment by thomas-mc-work** [comment]
Nice!

I've just noticed that you've chosen curl over wget. Debian and Ubuntu are both having only wget installed out of the box. And I've also recognized curl rather as an API tool with the regarding query options. But I leave that choice to you.

**Comment by mag37** [comment]
Ah thank you, good point. I prefer curl when I can but I'll adjust the readme! Maybe I'll just make two different examples.
