### ISSUE TITLE
[Feature Request] - Web Interface Productivity Improvements / Updates Suggestions 

### ISSUE THREAD

**Issue by nodecentral** [mag37/dockcheck#75]
Hi

I’ve been using Dockcheck for a while, but I do so entirely via the web interface. My process is to copy the names of the containers that have updates and then running a one time watch tower docker command line just with the ones I want to update.

Some Ideas for the web UI.

1) Have the ability to select the containers you want to update from the list (checkbox?) and have the ability to either generate the watchtower one time update command line with them populated , or better still execute the update for the ones selected too.
2) Show container images that can be pruned
3) Show the date/time when a container was last updated
4) Show the release number of the image current in use and what the new one is.
5) Show all Containers not running, and what options there are to update them (currently only shows running containers)

Many thanks

**Comment by mag37** [comment]
Sorry but this project is not the WebUI-project, that's a fork/spinoff you referring to - probably [palleri/DC](https://github.com/Palleri/DCW)

This project is the CLI base behind it - which have evolved to include things like notification addons, showing stopped containers, optional auto-prune, docker label options and more.
But it will not provide a WebUI :) Sorry.

**Comment by nodecentral** [comment]
Many thanks (sorry for posting here)

I’ve reposted it on the other repository.
