### ISSUE TITLE
dockcheck hangs when checking for updates

### ISSUE THREAD

**Issue by ghost** [mag37/dockcheck#78]
i'm running dockcheck as outlined per the readme, and for some reason recently it randomly stopped working and now hangs when checking for updates (commonly stuck on 10/34 or 15/34). i've let it sit  for hours to see if it will progress and it never does.

how can i go about troubleshooting how to resolve this?

**Comment by mag37** [comment]
That's odd. I just ran it on 3 different machines (with with 25+ containers) and had no issues at all.

Does it just sit without errors?

What you can do is to test-run the [extras/errorCheck.sh](https://github.com/mag37/dockcheck/blob/main/extras/errorCheck.sh) and see if you get any odd output. It'll just print all the variables from the containers.

Or you can try [extras/dc_brief.sh](https://github.com/mag37/dockcheck/blob/main/extras/dc_brief.sh) to just check for updates without doing anything more. (can also be done with `-n` option of the main script)

Or if you've got some bash experience you can add `set -x` on one of the first lines in the script and run it, to have it print all debugging.

**Comment by mag37** [comment]
@Buddinski88 - could you take a look at your containers? I'm worried this is breaking issues. 

Maybe check with 
```
docker inspect "ContainerNameHere" --format '{{index .Config.Labels "com.docker.compose.project.environment_file" }}'
```
Or if you test an update on a container you know has env-files.

(I mention you because you've been helping with env's before)

**Comment by mag37** [comment]
> replacing {DRIVE} with the actual file path doesn't work. it is hanging when checking for updates:
> 
> [#--------------------------] 1/33
> 
> etc.

That's even more odd then.. 

Ahh I think I got it.
I just did some testing with that image `docker.getoutline.com/outlinewiki/outline` and it does not work with the registry-checking.
If you test replacing that url with `outlinewiki/outline` from the docker-hub registry instead it should work.

Like this:
```
  outline:
    image: outlinewiki/outline
...
```

**Comment by mag37** [comment]
Thank you! 

I was a bit hasty it seems - should work now, bumped the version to force updates.
