### ISSUE TITLE
Enhancement request: update one by one

### ISSUE THREAD

**Issue by msrheidema** [mag37/dockcheck#8]
Is it possible to add an option to have the dockers update one by one instead of all at once.
I have a location where the internet is a bit slow and doing a `docker compose pull` kills the internet as it tries to update all the containers at once.
`docker compose pull dockername` however works as it just downloads one container at a time.

**Comment by mag37** [comment]
I'm not sure what you mean.
Right now you can choose selectively what containers you'd like to update with the numbered list.

But even if you choose to update all, the script itself do run `docker compose pull <dockername>`, one at a time waiting for the first before continuing to the second. 
And docker itself do only download a couple of layers at a time and completely update a container before going to the next.

Neither my script nor docker itself do download everything at once.

**Comment by mag37** [comment]
This is somewhat solved by [pull request #9](https://github.com/mag37/dockcheck/pull/9) by @maanoobh, as this will only update the specific service specified (even if other services in the same stack also got updates) and you can have more control over how much you'll update in each sequence. 

Closing as solved.
