### ISSUE TITLE
Everything times out and fails on non amd64 / arm64

### ISSUE THREAD

**Issue by yoyoma2** [mag37/dockcheck#80]
When using the [workaround for non amd64 / arm64](https://github.com/mag37/dockcheck#roller_coaster-workaround-for-non-amd64--arm64) everything times out and fails.

Adding the _--foreground_ argument to the newly introduced _timeout_ command fixes the problem. Did not test that argument on other platforms however.

**Comment by mag37** [comment]
Great catch! I was looking at `--foreground` when I implemented it but thought it wasn't necessary - but seems it is on some platforms! Just tried it on a pi2 and had issues without `--foreground` there.

I did some testing on amd64 and it seems to do work just fine, so I'll add it straight to main.
Thank you for reporting and looking into a solution, once again. :heart_eyes:

**Comment by mag37** [comment]
Pushed to main and bumped version [v0.4.4 release](https://github.com/mag37/dockcheck/releases/tag/v0.4.4).
Closing.

**Comment by yoyoma2** [comment]
Fantastic, 0.4.4 works great!
