### ISSUE TITLE
timeout: unrecognized option '--foreground' error message

### ISSUE THREAD

**Issue by cerealconyogurt** [mag37/dockcheck#83]
Describe the bug
Hi!, I am receiving error message after run dockcheck.sh
I am running 50 containers and the dockcheck scripts fails in each one

Screenshots

    Containers with errors, wont get updated:
    freshrss - timeout: unrecognized option '--foreground'
    BusyBox v1.31.1 (2024-06-12 03:04:13 CST) multi-call binary.

    Usage: timeout [-s SIG] SECS PROG ARGS

    Runs PROG. Sends SIG to it if it is not gone in SECS seconds.
    Default SIG: TERM.
    paperless_ngx - timeout: unrecognized option '--foreground'
    BusyBox v1.31.1 (2024-06-12 03:04:13 CST) multi-call binary.

    Usage: timeout [-s SIG] SECS PROG ARGS

Desktop (please complete the following information):

    Client:
    Version: 25.0.3
    API version: 1.44
    Go version: go1.21.6
    Git commit: 4debf41
    Built: Tue Feb 6 21:13:00 2024
    OS/Arch: linux/amd64
    Context: default

    Server: Docker Engine - Community
    Engine:
    Version: 25.0.3
    API version: 1.44 (minimum version 1.24)
    Go version: go1.21.6
    Git commit: f417435
    Built: Tue Feb 6 21:13:08 2024
    OS/Arch: linux/amd64
    Experimental: false
    containerd:
    Version: v1.7.13
    GitCommit: 7c3aca7a610df76212171d200ca3811ff6096eb8
    runc:
    Version: 1.1.12
    GitCommit: v1.1.12-0-g51d5e94
    docker-init:
    Version: 0.19.0
    GitCommit: de40ad0

**Comment by mag37** [comment]
Thank you for the report!
Seems like Busybox uses a different syntax for **timeout** and dont have the `--foreground` option.

I dont have an Alpine  (I'm guessing you're running Alpine) box up atm, I'll spin one up for testing tomorrow.

This might be a solution, removing line 228+229 and adding this prior to the for-loop at line 219

```sh
### Testing and setting timeout binary
t_out=$(builtin type -P "timeout") 
if [[ $t_out ]]; then
  t_out=$(realpath $t_out 2>/dev/null || readlink -f $t_out)
  if [[ $t_out =~ "busybox" ]]; then
    t_out="timeout -t ${Timeout}"
  else t_out="timeout --foreground ${Timeout}"
  fi
else t_out=""
fi
```

(hacked together on my phone in the middle of the night, excuse any syntax errors)

**Comment by mag37** [comment]
I dont have any experience with Alpine, but I'm aiming for the script to be as usable as possible.
I'm assuming you've installed bash-shell.

But as far as I can tell - with bash-shell installed and doing the change I posted above, it seems to work.
I push it to main as soon as I've done some more testing and if you'd like to test it out.
Either by copying the above and doing the changes yourself, or download the changed branch: https://github.com/mag37/dockcheck/blob/busyfix/dockcheck.sh

**Comment by cerealconyogurt** [comment]
Hey, thank for you support and super fast answer!.

I am using a Asustor NAS that uses a modified version of a full *nix distro busybox kind of like.
I will test it tomorrow since I am now traveling.

**Comment by cerealconyogurt** [comment]
I could not wait and I tested it from the phone :-)
It worked using the -n option:

```
[##################################################] 50/50

Containers on latest version:
baikal
code-server
database_backup
dozzle
duplicacy
excalidraw
fail2ban
filebot
filebrowser
flaresolverr
freshrss
frontend
gluetun
gotify
homepage
komga
languagetool
lingva
mealie
megacmd
mosquitto
netbootxyz
onedrive
paperless_ngx
paperless_ngx_db
paperless_ngx_redis
pgadmin
phpmyadmin
piwigo
piwigo_db
portainer-ce
prowlarr
pyload
radicale
recorder
scrutiny
searx
socket_proxy
stirling
syncthing
traefik
transmission
uptime-kuma
vaultwarden
vaultwarden_backup
wallabag
wallabag_db
wallabag_redis
watchtower

Containers with updates available:
metube

No updates installed, exiting.
```

I will test the other parameters tomorrow, but so far so good...

**Comment by mag37** [comment]
Wonderful! Thank you for testing it right away.

If it works with the -n option it should work with the rest as they don't modify the code block where timeout is used.

I'll run a few more tests tonight and push it to main after!
