### ISSUE TITLE
Gotify template

### ISSUE THREAD

**Issue by cerealconyogurt** [mag37/dockcheck#86]
Hey, I have a Gotify template working but I do not know how to add it here :-(

**Comment by mag37** [comment]
Oh, to contribute to the project? That's nice!

You can fork the project, add your modifications and then create a pull request. (See [here](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project) )

Or if you're not comfortable with that you can just paste it as a comment here - but then it wouldn't show up as you who made the changes/contributions (I'd tag you, but its not the same).

**Comment by cerealconyogurt** [comment]
I will fork the project, and then I create a pull request. Thanks!
