### ISSUE TITLE
Feature Request: Discord Webhook Notifications

### ISSUE THREAD

**Issue by XDark187** [mag37/dockcheck#98]
Hey, I would love to see this feature being added in the future.
Thank you

**Comment by mag37** [comment]
I will look into it later, can probably use something similar to [`notify_matrix.sh`](https://github.com/mag37/dockcheck/blob/main/notify_templates/notify_matrix.sh) or [`notify_telegram.sh`](https://github.com/mag37/dockcheck/blob/main/notify_templates/notify_telegram.sh).

**Comment by mag37** [comment]
I've got a template working, just doing some larger overhaul of the notification logics (the template wont work with current main) - so I'll push it with the rest when I'm ready.

**Comment by XDark187** [comment]
> I've got a template working, just doing some larger overhaul of the notification logics (the template wont work with current main) - so I'll push it with the rest when I'm ready.

Great, thanks for the effort

**Comment by XDark187** [comment]
There's a missing curly bracket at the end of the `notify_discord.sh` template @mag37

**Comment by mag37** [comment]
Thank you,
I had some testing in the end and must have deleted the curly by mistake when I removes those.
